### PR TITLE
allow custom ops to be deparsed

### PR DESCRIPTION
**Pull request by haarg**

### CODE REVIEW

**Comment by arc** [comment]
@haarg I was just about to merge this, but I see that the Travis checks are failing. It looks like that's problems with getting the relevant Perl versions, rather than anything to do with your PR, but would you mind taking a quick look at our .travis.yml and see if it's doing anything obviously wrong?

**Comment by haarg** [comment]
There were some issues with the travis threaded builds previously which should be fixed now.  The build still appears to be failing though, unrelated to anything in this PR.

**Comment by xsawyerx** [comment]
Is there a way we can bump this to be checked by Travis CI again or should we resubmit this as a new PR? (I'm willing to do that.)

**Comment by karenetheridge** [comment]
rebase the branch against the new master, force-push.

**Comment by xsawyerx** [comment]
Merged in #10. Thanks!

**Pull request closed without merging**
