### PR TITLE
adjust prereqs to fix travis runs

### PR DESCRIPTION
**Pull request by haarg**

### CODE REVIEW

**Comment by xsawyerx** [comment]
Can you explain why this fixes it? I would love to understand it.

**Comment by haarg** [comment]
The travis-perl helpers do a dzil build to create the dist before running the Makefile.PL or doing testing.  This is done using one of the recent perl builds that exist on the machines.  That perl install has a variety of modules preinstalled, including Devel::PPPort.  So the dzil build ends up overwriting the ppport.h from the repo with the one from whatever Devel::PPPort is already installed on the machine.  It appears that the preinstalled version is too old for Ref::Util::XS.  The travis-perl helpers satisfy the authordeps before doing a build, so adding an authordep on a newer Devel::PPPort gets it installed and used in the build.

Changing the Readonly dep to a develop recommends also means that the helpers will pick it up for the tests.  Previously it would sometimes install it in the wrong perl, because the correct perl isn't available until after the helpers init.

**Comment by xsawyerx** [comment]
The authordep is written as a comment there, though, isn't it?

**Comment by karenetheridge** [comment]
That's how authordeps are declared -- they are a special syntax that is grepped for in Dist::Zilla::App::Command::authordeps - nothing else uses it (it doesn't feed into the META.* prereqs).

**Comment by xsawyerx** [comment]
Ah, I see!

**Comment by xsawyerx** [comment]
Rebased and merged. 👍

**Pull request closed without merging**
