### PR TITLE
Move the common call checker logic into a function

### PR DESCRIPTION
**Pull request by JRaspass**
This shrinks the shared object by around 4KiB on an x64 Perl 5.26.1 (38400 -> 34352)

This seems like the right trade-off as the installation of the OP shouldn't be the hot path, and the smaller cache profile might be a larger win than the cost of the extra pointer traversal.

Either way I'm far from a C dev, so opinions?

### CODE REVIEW

**Comment by JRaspass** [comment]
Hmm, I don't get why travis is failing, it thinks things like OpHAS_SIBLING are undefined, but I would have thought master would have the same issue and than ppport.h would save us, hmm...

**Comment by karenetheridge** [comment]
ppport.h is not in the git repository -- it's supplied by Dist::Zilla. travis is just running Makefile.PL and does not do `dzil build`.

Either ppport.h needs to be committed to the repository, or a dzil build needs to be done by travis -- both is not horrible (and that's what I do in my XS repositories). I'll prepare a patch.

**Comment by xsawyerx** [comment]
Created https://github.com/p5pclub/ref-util-xs/pull/6 with a fix.

**Comment by JRaspass** [comment]
Rebased on top of the ppport.h changes, hopefully Travis now likes me :-)

**Comment by xsawyerx** [comment]
Merged from a cherry-picked branch. Thanks and sorry for all the hassle.

**Comment by JRaspass** [comment]
Thanks @xsawyerx, that deparse code looks fun too, think I'll copy that for my work on custom ops in List::Util :-)

**Pull request closed without merging**
